apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: so-selfsigned-ca
spec:
  isCA: true
  commonName: so-selfsigned-ca
  secretName: echo-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
